package com.docmate.common.enums;

public enum NotificationType {
    EMAIL,
    SMS,
    PUSH_NOTIFICATION,
    IN_APP_NOTIFICATION,
    APPOINTMENT_REMINDER,
    APPOINTMENT_CONFIRMATION,
    APPOINTMENT_CANCELLATION,
    APPOINTMENT_SCHEDULED,
    PRESCRIPTION_READY,
    PAYMENT_CONFIRMATION,
    PAYMENT_FAILED,
    PAYMENT_RECEIVED,
    WELCOME_MESSAGE,
    PASSWORD_RESET,
    EMAIL_VERIFICATION,
    SYSTEM_ALERT,
    DOCTOR_APPROVED,
    DOCTOR_REJECTED
}
