spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:docmate_platform}
    username: ${DB_USERNAME:docmate}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: false  # Disabled - using centralized db-migration service

server:
  port: ${PORT:8084}
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.docmate: ${LOG_LEVEL:INFO}
    org.springframework.security: ${LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Stripe Configuration
stripe:
  api:
    key: ${STRIPE_SECRET_KEY:sk_test_your_stripe_secret_key_here}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET:whsec_your_webhook_secret_here}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:docmate-secret-key-for-jwt-token-generation-2024}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: desc
